# Site settings
title: FedRAMP.gov
description: The Federal Risk and Authorization Management Program, or FedRAMP, is a government-wide program that provides a standardized approach to security assessment
# the subpath of your site, e.g. /blog/
# baseurl: "https://www.fedramp.gov" # the subpath of your site, e.g. /blog/
# # the base hostname & protocol for your site
url: "https://www.fedramp.gov" # the base hostname & protocol for your site
logo: /assets/img/logo-main-fedramp.svg
feature_image: /assets/img/feature-background.jpg

# the GitHub name-with-owner, needed for the github-metadata plugin
# ref: https://github.com/jekyll/github-metadata/blob/master/docs/configuration.md#configuration
#repository: gsa/fedramp-gov

logo-mobile: /assets/img/logo-mobile-fedramp.svg
logo: /assets/img/fedramp-logo-vert.svg
feature_image: /assets/img/feature-background.jpg

colors:
  background: '#ffffff'
  link:
    color: '#1A4480'
    active: '#1A4480'
    hover: '#CC1D1D'
    visited: '#CC1D1D'
  button:
    background: '#112e51'
    hover: '#002E4D'
    text: '#fff'
  headers: '#205493'
  text: '#4c4c4e'
  reverse_text: '#ffffff'
  projects:
    accent: '#02bfe7'
    card-heading: '#0071bc'
  banner:
    background: '#112e51'
    text: '#fff'
    button:
      background: '#dce4ef'
      text: '#112e51'
  footer:
    primary-background: '#f1f1f1'
    secondary-background: '#d6d7d9'
    text: '#4c4c4e'

analytics:
  google:
    code: 'UA-48605964-32' # Change this to your GSA analytics code
  dap:
    agency: GSA    # Change this to your agency
    subagency: TTS # Change this to your agency

defaults:
 -
  scope:
    path: "" # an empty string here means all files in the project
  values:
    layout:
      - home
      - page
      - "project-list"
      - project
      - "team-list"
      - team
      - posts
      - policy 

forms:
- type: newsletter
  heading: Add your email to FedRAMP's subscriber list.
  url: https://public.govdelivery.com/accounts/USGSA/subscriber/topics?qsp=USGSA_2224
  button: Subscribe
  privacypolicy: Your privacy and security are important to us, we'll only share your information as described in the <a href="http://www.gsa.gov/portal/content/116609">GSA Privacy and Security Notice</a>

footer:
  links:
  image: /assets/img/fedramp-logo-stamp.png
  contact:
    name:
    email: info@FedRAMP.gov
    twitter: FedRAMP
    facebook:
    youtube:
    rss:
  text: General Services Administration 1800 F Street, NW, Washington, DC 20006

# Build settings
markdown: kramdown
include:
  - _navigation.json
exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-last-modified-at

paginate: 5
paginate_path: "/blog/page:num/"

# Inititalize project and team collections
collections:
  projects:
    output: true
  team:
    output: true
  posts:
    output: true
  policy:
    output: false

sass:
    style: compressed

wds-version: 2.8.0

theme: jekyll-theme-time-machine
